# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# Specify Workspace
workspace 'superez-app'

target 'superez-app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for superez-app

  pod 'AppAuth', '>= 0.94'
  pod 'Stripe', '~> 11.2.0'

end
